spring:
  datasource:
    url: jdbc:h2:mem:TESTDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # You can use 'update' for non-test scenarios
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: H2
