spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weblibrary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: false
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: ${JWT_SECRET:aLut6aqXn5dHrk71nU8YJURu5zXosVTXGSgc3xDiLHS}
  expiration: 86400000
  refresh-expiration: 604800000
