version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "228:228"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build:
      context: ../../WebstormProjects/weblibrary  # Путь к React-проекту
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:228

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=0098
      - MYSQL_DATABASE=weblibrary
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: