#spring:
#  profiles:
#    group:
#      prod: prod
#      docker: docker
#
#---
#spring:
#  config:
#    activate:
#      on-profile: docker
#  datasource:
#    url: jdbc:mysql://db:3306/weblibrary?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: 0098
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#  web:
#    resources:
#      static-locations: classpath:/static/
#  mvc:
#    throw-exception-if-no-handler-found: true
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: jdbc:mysql://<host>.planetscale.com:3306/weblibrary?useSSL=true&serverTimezone=UTC
#    username: your_username
#    password: your_password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#  web:
#    resources:
#      static-locations: classpath:/static/
#  mvc:
#    throw-exception-if-no-handler-found: true